services:
  - type: web
    name: wms-backend
    runtime: java
    buildCommand: cd wms && ./mvnw clean package -DskipTests
    startCommand: cd wms && java -jar target/wms-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: ZHIPU_API_KEY
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_REDIS_HOST
        sync: false
    plan: free